### ISSUE TITLE
Linux is  in /tmp no /home/{user}/tmp

### ISSUE THREAD

**Issue by alejonext** [bruce/node-temp#37]
Well,  when the install is global in linux. 
```javascript
var temp = require('temp');
console.log(require('os').tmpDir, temp.dir);
```
Print
```console
/tmp /home/{user}/tmp
```

**Comment by RobLoach** [comment]
This should be fixed. What version of node are you on? Seems to work on 0.10, and 0.12.

**Comment by bruce** [comment]
Tested on fresh Linux instances as root, with the library installed globally, and Node `v0.12.4`, `v0.11.16`, and `v0.10.38` without being able to reproduce (in all cases `temp.dir` was `/tmp`). Please reopen with specific linux and node versions (and any other steps to reproduce) if you are still encountering this issue.
