### ISSUE TITLE
Can't pipe into temp.createWriteStream

### ISSUE THREAD

**Issue by stereokai** [bruce/node-temp#38]
@bruce, this is a recommended syntax for copying a file with node.js:
```js
fs.createReadStream('file.html')
  .pipe(fs.createWriteStream('newfile.html'));
```

However it doesn't seem to work with `node-temp`:
```js
fs.createReadStream('file.html'))
  .pipe(temp.createWriteStream()); // temp file created, 0 bytes written
```

Of course, the following syntax (from your docs) does work (a sanity check):
```js
temp.open('tempfile', function (err, info) {
  fs.write(info.fd, fs.readFileSync('file.html').toString());
  fs.close(info.fd, function (err) {
    if (err) throw err;
    // Do something with the file
  });
});
```

Looking at the [code for `temp.createWriteStream()`](https://github.com/bruce/node-temp/blob/master/lib/temp.js#L264-L269), it seems it returns a stream just like the original `fs` api. Am I doing something wrong? Am I missing anything here?

**Comment by mastilver** [comment]
Hi

Did you try: `temp.createWriteStream('temp.html)` ?

**Comment by stereokai** [comment]
Thanks for replying! I have actually neglected that project some time ago,
but will pick it back up in around a month or two - hopefully you will be
available to attend to me then :)

**Comment by bruce** [comment]
I've tested this with the following and have no problems. Is it possible you weren't waiting for the `finish` event? Closing; let me know if you run into this issue again and we can work through it. (I'll add this to the better test suite I'm building currently.)

```javascript
var pipeTo = temp.createWriteStream();
fs.createReadStream('package.json')
  .pipe(pipeTo)
  .on('finish', function() {
    assert.ok(fs.statSync(pipeTo.path), 'Did not create destination path');
    var source = fs.readFileSync('package.json').toString();
    var destination = fs.readFileSync(pipeTo.path).toString();
    assert.equal(source, destination);
  });
```
