### ISSUE TITLE
Directory doesn't get deleted

### ISSUE THREAD

**Issue by zimt28** [bruce/node-temp#43]
First, here's my code:

```
readStream = share.airwayBills.findOne().createReadStream();

temp.track();

temp.mkdir('pdfgen', function(err, info) {
  var writeStream = fs.createWriteStream(path.join(info, 'out.pdf'));

  readStream.pipe(writeStream);

  writeStream.on('finish', function() {
    temp.cleanup(function(err, stats) {
      console.log(stats);
    });
  });
});
```

Works great, except for deleting the directory: the log is `{ files: 0, dirs: 0 }` and the directory still exists.
How can I fix this? Thanks!

**Comment by axelwass** [comment]
I am experiencing a similar issue. I'm getting this error message on automatic cleanup: `Error: ENOTEMPTY: directory not empty, rmdir 'c:\***\***'`

**Comment by aleclarson** [comment]
Take note that `ctrl+c` sends a "SIGINT" signal, and that **doesn't** trigger `process.on("exit", ...)` handlers. Not sure if that's your problem or not, but it may help someone else.

The workaround:
```js
process.once('SIGINT', () => process.exit());
```

**Comment by miguelsolano** [comment]
Seeing as there wasn't a reply after @aleclarson, I am going to close this issue. Please re-open if you have any issues.
