### ISSUE TITLE
On Mac 10.9 with node 0.10.40, throws an error cannot find module rimraf

### ISSUE THREAD

**Issue by mani-mishra** [bruce/node-temp#45]
The rimraf js is present in the node_modules/rimraf/ , in the same folder as temp.js and at the global scale too. Still, the module loading is failing.

Doesn't seem to happen on ubuntu 12.04 with node 0.10.38

**Comment by miguelsolano** [comment]
It's been so long, so i'm closing this issue. If it is still an issue please re-open the issue.
