### ISSUE TITLE
An example in the README is incorrect

### ISSUE THREAD

**Issue by sithmel** [bruce/node-temp#50]
Please correct the readme. The write method requires a callback. Without it, it will fail randomly returning "Error: EBADF: bad file descriptor, write"

```
fs.write(info.fd, myData, function (err) {
  fs.close(info.fd, function(err) {
    exec("grep foo '" + info.path + "' | wc -l", function(err, stdout) {
      util.puts(stdout.trim());
    });
  });
});
```

**Comment by UziTech** [comment]
@sithmel could you create a PR?

**Comment by miguelsolano** [comment]
@UziTech Mind creating a PR for this and i'll merge it tonight?

**Comment by miguelsolano** [comment]
Issue has been resolved.
