### ISSUE TITLE
How to create temp file in user defined temp directory

### ISSUE THREAD

**Issue by akris100** [bruce/node-temp#52]
I would like to create the temp file in a different directory other than System temp directory.
Is it possible?

**Comment by martinduartemore** [comment]
Yes, it is possible. When requiring a path, for example, you can set the [Affixes](https://github.com/bruce/node-temp#affixes) of the file. The ``dir`` option allows you to choose a custom directory path. I'll give you an example. This is what I would do to get a temporary file name in the directory of the script being executed:

```javascript
var temp = require("temp");
var tempName = temp.path({dir:__dirname});
// Do something with tempName
```

So, for file creation, you would do something like this:
```javascript
var temp = require("temp");
temp.open({dir:__dirname}, function(err, info) {
    // Do something here
});
```
I hope this helps.

**Comment by akris100** [comment]
Hi Martin,
Thank you very much. Kris

**Comment by miguelsolano** [comment]
Closing this issue, since this appears to be solved. 👍
