### ISSUE TITLE
incompatible with gulp

### ISSUE THREAD

**Issue by OverDrone** [bruce/node-temp#53]
there is a gulp extension, called gulp-jspm. It uses this module. due to gulp multithreading nature, process.exit event is called for each gulp task, not for node.js process termination. 
Example gulp config from spring: [gulpfile.zip](https://github.com/bruce/node-temp/files/325732/gulpfile.zip)
actual scenario (3 concurrent threads):
[1] jspm-main started
TempFile1 is created, temp.filesToDelete=[TempFile1], temp listener initialized
[2] jspm-maps started
TempFile2 is created, temp.filesToDelete=[TempFile1, TempFile2]
[3] jspm-admin started
TempFile3 is created, temp.filesToDelete=[TempFile1, TempFile2, TempFile3]
[2] jspm-maps processing
[2] jspm-maps finished
process.exit event called, cleanupFilesSync deleting ALL 3 TEMP FILES! TempFile1, TempFile2, TempFile3 instead of just TempFile2
[3] jspm-admin processing
ERROR: file TempFile3 not found
[1] jspm-main processing
ERROR: file TempFile1 not found

In short, temp module (with it's state filesToDelete) is global to all 3 gulp tasks which leads to conflicts.
Yes, there is a workaround: DO NOT execute jspm gulp tasks in parallel. But it's a gulp main feature. You would just use grunt or pure npm otherwise.
I suggest a fix. Just change temp module functions to:

```
function deleteFileOnExit(filePath) {
  if (!tracking) return false;
  var onExit = function() {
    rimrafSync(filePath);
  };
  process.addListener('exit', onExit);
}

function deleteDirOnExit(dirPath) {
  if (!tracking) return false;
  var onExit = function() {
    rimrafSync(dirPath);
  };
  process.addListener('exit', onExit);
}
```

It would work for all environments, standalone, grunt, gulp, you name it.
replace current functionality completely or just add new functions like track2/open2 with suggested functionality

**Comment by hedefalk** [comment]
I think I just struck this.

**Comment by UziTech** [comment]
@OverDrone would you be able to create a PR?
