### ISSUE TITLE
Collisions from temp.path()

### ISSUE THREAD

**Issue by ShadSterling** [bruce/node-temp#54]
I've been getting the same filename from temp.path() every time my express.js server gets the same request repeated close together (when I doubleclick the button in the browser that triggers the request).

**Comment by miguelsolano** [comment]
@ShadSterling If this issue is still relevant would you mind providing some error messaging or sample code? With the current information presented I don't have enough to go on.

**Comment by ShadSterling** [comment]
It's not still relevant.  The project I think I was trying to use it for has moved on using a different method for generating unique names for temp files.  Making a simple test to reproduce the problem didn't generate any collisions.

**Comment by miguelsolano** [comment]
Got it, i'm closing the issue for now to keep the repo clean. If the problem arises again feel free to reopen the issue.
