### ISSUE TITLE
[Race Condition] cleanup() can be too destructive

### ISSUE THREAD

**Issue by moloughlin** [bruce/node-temp#60]
A node process that has called temp.track() will have a single process-wide array of files that have been opened and calling temp.cleanup() will delete all of these files.

There is a race condition here where one request could open a temp file but before it has the chance to be used, it can be deleted by some other concurrent request hitting a cleanup() call. Since some node processes tend to be very long-running, simply leaving the files until exit runs the risk of disk filling or having a large batch deletion to perform on exit.

It would be nice to have a middle-ground where file deletion is made more precise so we have the means to avoid this case.

**Comment by mmclau14** [comment]
definitely agree with this use case. i am creating a project where i have to do this as well. it would be able to great to be able to categorize the files at least under a string that is passed

**Comment by harlentan** [comment]
https://www.npmjs.com/package/tmp  may be another choice to avoid cleanup race
