### ISSUE TITLE
Dates in NPM metadata are wrong

### ISSUE THREAD

**Issue by Mystere** [bruce/node-temp#64]
The NPM metadata lists dates that do not follow the proper time format, this causes some apps (notably Artifactory) to fail, throwing an invalid format exception (they use Joda time to parse it, and it fails).

Those dates are below, notice that they do not have a sub-second time, but the rest of the dates do:

"time": {
        **"created": "2010-11-09T23:36:39Z",**
        "modified": "2017-08-16T01:34:42.039Z",
        **"0.2.0": "2010-11-09T23:36:39Z",**
        "0.3.0": "2011-12-30T04:56:26.911Z",
        "0.4.0": "2012-01-02T06:06:13.789Z",
        "0.5.0": "2012-12-27T06:05:40.975Z",
        "0.5.1": "2013-06-30T05:34:31.247Z",
        "0.6.0": "2013-09-09T06:30:45.938Z",
        "0.7.0": "2014-02-26T09:14:42.595Z",
        "0.8.0": "2014-06-02T04:56:15.496Z",
        "0.8.1": "2014-08-05T00:12:17.410Z",
        "0.8.2": "2015-06-08T16:50:31.181Z",
        "0.8.3": "2015-06-08T16:55:52.866Z"
    },

http://registry.npmjs.com/temp

Error is:

{
  "errors" : [ {
    "status" : 500,
    "message" : "Invalid format: \"2010-11-09T23:36:39Z\" is malformed at \"Z\""
  } ]
}

You might be inclined to say that this is an Artifactory problem, or a joda time problem... that the date format is acceptable.   However, I have found no other packages in npm that have this issue... temp is the only one.   

Maybe you think it's an npm issue, and maybe it is.  But as a user, there seems to be no way for me to fix this.. so maybe there is something on your end that can be done.

**Comment by tkryskiewicz** [comment]
Hey,

How are those dates resolved? Would removing this release fix it?

**Comment by UziTech** [comment]
I don't think this is something we can fix
