### ISSUE TITLE
MAINTAINER NEEDED

### ISSUE THREAD

**Issue by bruce** [bruce/node-temp#67]
If you're interested in taking over maintenance of this project, please let me know; I've been pulled away for some time. (As you can probably tell)

**Comment by miguelsolano** [comment]
I'd be interested in becoming a maintainer!

**Comment by bruce** [comment]
@miguelsolano Wonderful! I'll add you as a collaborator; if you have some time to go through and look through the issues/PRs, that would be very helpful! If you're still into it here in a few days I'll be happy to pass over releases!

**Comment by miguelsolano** [comment]
@bruce Created a milestone, have closed a few issues, and opened a PR, let me know what you think. Enjoying it so far though!

**Comment by UziTech** [comment]
I could be a collaborator. I don't have time to take the project over but I could help out @miguelsolano

**Comment by UziTech** [comment]
@BinaryMuse Atom uses this pretty heavily. Maybe they would like to take over development?

**Comment by UziTech** [comment]
@bruce @miguelsolano If you guys need some help I would be open to helping with a few issues/PRs

**Comment by miguelsolano** [comment]
@bruce would you feel comfortable passing the releases off to me?

**Comment by miguelsolano** [comment]
@UziTech That's more of a question for Bruce. But for right now feel free to create any PRs that you think would help or jump in and respond to some of the issues. I can review and merge your PRs 👍

**Comment by 50Wliu** [comment]
@miguelsolano @bruce any chance a new release can be created?  Looks like there's been some great PRs merged recently.

**Comment by UziTech** [comment]
I would be willing to help out. I'll take a look at the issues and see what I can do.

**Comment by paulmelnikow** [comment]
I noticed there was a new contributor; thanks for your work! I’d also be happy to help as needed!

**Comment by UziTech** [comment]
@miguelsolano I have commented on a few of the pull requests. Could you merge some of them and create a new release?

**Comment by miguelsolano** [comment]
Absolutely, I get off work soon. I will work on this tonight!

**Comment by UziTech** [comment]
@miguelsolano are you still working on this repo?

**Comment by paulmelnikow** [comment]
For what it’s worth, I’d still be happy to jump in on this!

In particular I’ve done some work on tmp-promise which I think ought to be merged into this project, since promises are the primary way of doing async these days.

**Comment by UziTech** [comment]
I do have a PR to add promises to this repo #78

**Comment by paulmelnikow** [comment]
Ah nice, I hadn't seen that! I just posted a comment in that PR.

**Comment by UziTech** [comment]
@bruce I'm not sure where @miguelsolano is. According to his [contribution graph](https://github.com/miguelsolano) he dropped off of GitHub. I have tried reaching him via email as well with no reply. Are you able to make me a contributor and give me publish access on npm to continue maintaining this package?

**Comment by UziTech** [comment]
I also created an organization [node-temp](https://github.com/node-temp) that we could transfer this package to so we can continue to maintain this package.

**Comment by UziTech** [comment]
@miguelsolano your back!! Are you able to move the repository over to the node_temp organization?

**Comment by miguelsolano** [comment]
I am! Unfortunately, I can’t, but I am dead set on keeping this repo on
good standing. Would you mind hopping on a call sometime?

**Comment by bruce** [comment]
@UziTech I'm happy to move it if @miguelsolano gives the 👍

**Comment by miguelsolano** [comment]
@UziTech I'll actually email you instead 👍

**Comment by UziTech** [comment]
@miguelsolano You can send me an email at tony@brix.ninja

**Comment by miguelsolano** [comment]
@bruce I've talked with @UziTech and we concluded that it'd be ok to transfer the repository to me and I could maintain it and add him as a collaborator. So if you were still interested and were willing i'd love to get this repo transferred to me. 

Please let me know your thoughts! 

Thanks!

**Comment by UziTech** [comment]
@bruce could we get this repository moved so we are able to update it? either to @miguelsolano or to @node-temp doesn't matter to me.

**Comment by UziTech** [comment]
@miguelsolano @bruce are you able to add me as a collaborator so we can have more than one person working on this?
