### ISSUE TITLE
Jasmine Tests

### ISSUE THREAD

**Issue by mgn2486** [bruce/node-temp#75]
I have the following code that i have to write tests for. I want to test if a call was made to "readdir" and as well as tests if an error occurred in the Promise the "logger.error" is called and if an error doesn't occur the promise is resolved. I'm Still new to Jasmine tests, please help. In my approach i keep getting an error : "Unhandled rejection TypeError: path must be a string or Buffer"

**Code Snippet:**

const MyPromise = require('bluebird');;
const chalk = require('chalk');
const fs = require('fs');
const logger = require('./logger');

function LocalFileLister(settings) {
    this._settings = settings;
};

LocalFileLister.prototype.listAllFiles = function() {
    logger.trace('  [FILE] List All Files (using local disk)');
    return new MyPromise((resolve, reject) => {

        fs.readdir(this._settings.dropLocation, function(error, files){
            if (error) {
                logger.error('localFileLister.js -> listAllFiles');
                logger.error(error);
                reject(err);
            } else {
                logger.trace('  [FILE] List All Files complete (using local disk): '+ files.length +' files(s) found');
                resolve(files);
            }
        });
    });
};

**My - Approach**

var LocalFileLister = require('./LocalFileLister');
var fs = require('fs');

describe("Local file listing", () =>{  
        beforeEach((done) => {
            settings = jasmine.createSpyObj('settings', ['settings']);
            fs = jasmine.createSpyObj('fs', [ 'readdir']);
            fs.readdir.call(function() {
                return true;
            });

            var sut = new LocalFileLister([]);

            sut.listAllFiles((done) => {
                return new MyPromise((r)=>{
                    fs.resolve(r);
                    done();
                });
            });
        });

        it("should call listAllFiles", ()=>{
            expect(sut.listAllFiles).toHaveBeenCalled();
        });      
});

**Comment by UziTech** [comment]
This doesn't seem to have anything to do with `temp`
