### ISSUE TITLE
Missing 0.9.1 tag

### ISSUE THREAD

**Issue by harrysarson** [bruce/node-temp#83]
Hi!

I noticed that 0.9.1 has been released on npm but there is no 0.9.1 tag on github. I thought it might be helpfull to flag this 🙂 

Best

**Comment by miguelsolano** [comment]
Oops. I’ll make sure to do that tonight 👍🏽

**Comment by harrysarson** [comment]
Thanks!

**Comment by miguelsolano** [comment]
tag has been made!
