### ISSUE TITLE
Old-style octals in /lib/temp.js

### ISSUE THREAD

**Issue by arantes555** [bruce/node-temp#91]
In `/lib/temp.js`, at lines 265 and 276, there are old-style octal numerals `0700`, which are deprecated, and forbidden in strict mode.

While this is valid JavaScript, it can cause problems in certain cases. For example rollup does not like mixing the old syntax and the newer ES6 features : it fails on temp@0.9.2 whereas it succeeds on 0.9.1. (I have to admin, I am not sure exactly why).

I suggest to move this to the modern octal syntax `0o700` instead. Another possibility would be to use the same syntax as a few lines below `parseInt('0600', 8)`.

**Comment by UziTech** [comment]
@arantes555 can you create a PR to update it?

**Comment by arantes555** [comment]
@UziTech done

**Comment by miguelsolano** [comment]
@arantes555 Merged!

**Comment by arantes555** [comment]
Great, thanks for the amazing reactivity ! Is it possible to publish a 0.9.3 with this ? (and to push the tag of this to github ^^ I got quite confused by the 0.9.2 release !)

**Comment by miguelsolano** [comment]
🤦 Oh no.... I forgot to do that. So sorry!!!!! I'll jump on that right now. Just have to drive home really quick!
