### ISSUE TITLE
Broken Node 4 compatibility 

### ISSUE THREAD

**Issue by vrahlin** [bruce/node-temp#93]
PR https://github.com/bruce/node-temp/pull/89 broke Node 4 compatibility purely because some 'var' were replaced with 'let'.  There was no advantage of using 'let', all declarations that were replaced were either global scope or function scope.  'const' (for global package imports)  or 'var' can be used with the same effect and it will maintain Node 4 compatibility.

**Comment by UziTech** [comment]
Node v4 is no longer supported and is insecure. The solution to that problem is to upgrade the version of node to >=v6.0.0 or downgrade the version of node-temp to <=v0.9.0.

**Comment by miguelsolano** [comment]
@vrahlin  Node 4 has been on End-of-Life for a few years now. It'd be hard to tailor the package for the present and legacy versions as well. I think our suggestion would be to either Upgrade Node or downgrade node-temp.

**Comment by vrahlin** [comment]
We are well aware of node 4 been old, not supported and insecure, nevertheless we are stuck with it due to various reasons.  It is running in private space.  Downgrading node-temp is also not an option since we are not importing it directly but it is imported by another module. I can understand if node 4 compatibility was broken to take advantage of new features or even if the code was systematically updated to use 'const' and 'let' instead of 'var' throughout the entire code, but simply changing a random subset of declarations from 'var' to 'let' does not seem to achieve anything, especially since the variables in question already have global or function scope.

**Comment by miguelsolano** [comment]
There is a plan to do a complete refactor to update to the LTS version of Node and release a new version of node-temp. Our tavisci didn't even test against Node 4 and it hasn't for quite sometime. The refactor was meant to be introduce incrementally so we can restructure the code to the point of being able to refactor to modern constructs and encourage open source contribution to the package. 

That being said, I apologize the package broke your system. Which package is depending on node-temp that you have a hard dependency on?

**Comment by vrahlin** [comment]
https://github.com/ragnar-johannsson/rsautl is the module we import and it depends on node-temp.

**Comment by UziTech** [comment]
You can use [Selective Version Resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) if you use yarn. Or you can edit the `package-lock.json` and use a lower version.

**Comment by UziTech** [comment]
or [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) with npm

**Comment by vrahlin** [comment]
Thank you @UziTech - we will look into that.

**Comment by UziTech** [comment]
Just a word of warning, I'm not sure I would trust security software that hasn't been updated in 5 years.

**Comment by vrahlin** [comment]
Yes, we understood security implications.  It is running in a controlled, closed environment.  We do not use yarn, and npm-force-resolutions requires npm v5 or above to support package-lock.json, we have npm v2 (yes, I know, it is old and not secure)

**Comment by miguelsolano** [comment]
@vrahlin I think the best we can do is to create a PR to that repo and target the node-temp version that would work for you all. Otherwise, you might have to fork and update the package.json yourself. So sorry for the inconvenience.
